version: '3.4'
services:
  database:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dunder1!
      MYSQL_USER: mscott
      MYSQL_PASSWORD: dunder1!
      MYSQL_DATABASE: office
